# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynstagram', '0002_auto_20171216_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
