# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pynstagram', '0003_auto_20171216_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photograph',
            options={'ordering': ['-created']},
        ),
    ]
